replicaCount: 1
image:
  apiGateway:
    repository: anwirisme/spring-petclinic-api-gateway
    tag: main
  customersService:
    repository: anwirisme/spring-petclinic-customers-service
    tag: main
  vetsService:
    repository: anwirisme/spring-petclinic-vets-service
    tag: main
  visitsService:
    repository: anwirisme/spring-petclinic-visits-service
    tag: main
  genaiService:
    repository: anwirisme/spring-petclinic-genai-service
    tag: main
  configServer:
    repository: anwirisme/spring-petclinic-config-server
    tag: main
service:
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  configServer:
    port: 8888
    nodePort: 30087
  apiGateway:
    port: 8080
    nodePort: 30082
